name: ai_guide
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.0
  just_audio: any
  just_audio_windows: any
  loading_animation_widget: any
  bloc: ^8.1.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  json_annotation: ^4.6.0
  attraction_repository:
    path: packages/attraction_repository
  attraction_api:
    path: packages/attraction_api

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.0
  mocktail: ^1.0.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

