name: landmark_repository
description: A Dart Repository which manages the google_maps_api domain.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.6.0
  google_maps_api:
    path: ../google_maps_api

dev_dependencies:
  build_runner: ^2.4.6
  coverage: ^1.0.3
  json_serializable: ^6.3.1
  mocktail: ^1.0.0
  test: ^1.16.4
